/**
 * Live pixel renderer for the castle world map.
 *
 * The terrain comes from src/data/worldmap.json (generated by tools/worldmap.py): a base colour layer,
 * a terrain-kind layer and an area layer. Every frame we recolour tiles from game state — floods,
 * fires, spills, smog, drought, quakes, melting snow, rising seas, ocean health — then draw the
 * animated sprites (factories, turbines, boats, lighthouse, dam), player-built buildings and castles.
 * Pure function over a pixel buffer: no DOM, so it is testable in Node.
 */
import world from "../../../../src/data/worldmap.json";
import { DISASTERS } from "./content";
import { PROVINCES, districts } from "./provinces";
import type { GameState } from "./types";

export const MAP_W = world.w;
export const MAP_H = world.h;
type RGB = [number, number, number];
const rgb = (hex: string): RGB => [
  parseInt(hex.slice(1, 3), 16),
  parseInt(hex.slice(3, 5), 16),
  parseInt(hex.slice(5, 7), 16),
];
const KIND = Object.fromEntries(world.kinds.map((k, i) => [k, i])) as Record<
  string,
  number
>;
const NONE = 255;

const C = {
  ink: rgb("#1a120a"),
  rock: rgb("#776e60"),
  rockD: rgb("#5c554a"),
  shallow: rgb("#2b6fa0"),
  flood: rgb("#6ab8cc"),
  foam: rgb("#9fd6e4"),
  wave: rgb("#3b6ea8"),
  murk: rgb("#3c5446"),
  ash: rgb("#3a3632"),
  ashL: rgb("#4e4842"),
  ember: rgb("#e8642c"),
  emberY: rgb("#f5c542"),
  soil: rgb("#8a6238"),
  dry: rgb("#b8982e"),
  sludge: rgb("#6e6230"),
  sludgeD: rgb("#4e4520"),
  smoke: rgb("#c9c9c9"),
  smokeD: rgb("#6b6b72"),
};
const FLAG: Record<string, RGB> = {
  highland: rgb("#a07ad6"),
  verdant: rgb("#7fd65a"),
  forge: rgb("#f08a3c"),
  tidehaven: rgb("#46d6d0"),
};

export interface WorldLayers {
  base: Uint8Array;
  palette: RGB[];
  kind: Uint8Array;
  area: Uint8Array;
  near: Uint8Array;
  distWater: Uint8Array;
  distSea: Uint8Array;
  hash: Uint8Array;
}

function unrle(runs: number[]): Uint8Array {
  const out = new Uint8Array(MAP_W * MAP_H);
  let o = 0;
  for (let i = 0; i < runs.length; i += 2) {
    out.fill(runs[i], o, o + runs[i + 1]);
    o += runs[i + 1];
  }
  return out;
}
function fromBase64(s: string): Uint8Array {
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
/** 4-neighbour distance (capped at 255) from every tile matching `source`. */
function distance(kind: Uint8Array, source: (k: number) => boolean) {
  const dist = new Uint8Array(kind.length).fill(255);
  let frontier: number[] = [];
  kind.forEach((k, i) => {
    if (source(k)) {
      dist[i] = 0;
      frontier.push(i);
    }
  });
  for (let d = 1; d < 255 && frontier.length; d++) {
    const next: number[] = [];
    for (const i of frontier) {
      const x = i % MAP_W;
      for (const j of [
        i - MAP_W,
        i + MAP_W,
        x > 0 ? i - 1 : -1,
        x < MAP_W - 1 ? i + 1 : -1,
      ])
        if (j >= 0 && j < kind.length && dist[j] === 255) {
          dist[j] = d;
          next.push(j);
        }
    }
    frontier = next;
  }
  return dist;
}

let cached: WorldLayers | undefined;
export function worldLayers(): WorldLayers {
  if (cached) return cached;
  const kind = unrle(world.kind);
  const hash = new Uint8Array(MAP_W * MAP_H);
  for (let i = 0; i < hash.length; i++) {
    let h = Math.imul(i ^ 0x9e3779b9, 0x85ebca6b);
    h = Math.imul(h ^ (h >>> 13), 0xc2b2ae35);
    hash[i] = (h ^ (h >>> 16)) & 255;
  }
  cached = {
    base: fromBase64(world.base),
    palette: world.palette.map(rgb),
    kind,
    area: unrle(world.area),
    near: unrle(world.near),
    distWater: distance(kind, (k) => k <= KIND.water),
    distSea: distance(kind, (k) => k <= KIND.shallow),
    hash,
  };
  return cached;
}

const isSea = (k: number) => k <= KIND.shallow;
const lowland = (k: number) =>
  k === KIND.grass ||
  k === KIND.pasture ||
  k === KIND.field ||
  k === KIND.marsh ||
  k === KIND.beach ||
  k === KIND.forest;
const mix = (a: RGB, b: RGB, t: number): RGB => [
  a[0] + (b[0] - a[0]) * t,
  a[1] + (b[1] - a[1]) * t,
  a[2] + (b[2] - a[2]) * t,
];

export interface AreaStatus {
  effects: Set<string>;
  buildings: string[];
  damaged: number;
}
/** What is happening in each castle area right now, from the simulation districts beneath it. */
export function areaStatus(state?: GameState): AreaStatus[] {
  return PROVINCES.map((p) => {
    const tiles = state ? districts(state, p) : [];
    const hit = tiles.filter((t) => t.disruption > 0 && t.effect);
    return {
      effects: new Set(hit.map((t) => t.effect as string)),
      buildings: tiles.filter((t) => t.building).map((t) => t.building!),
      damaged: hit.length,
    };
  });
}

/** Snow at lower altitude melts first as the planet warms (climate is °C above baseline). */
const meltThreshold = (y: number, h: number) =>
  3 - (Math.min(y, 50) / 50) * 2.6 + (h / 255 - 0.5) * 0.4;

function terrainPixel(
  L: WorldLayers,
  i: number,
  frame: number,
  status: AreaStatus[],
  climate: number,
  ocean: number,
): RGB {
  const x = i % MAP_W,
    y = (i / MAP_W) | 0,
    k = L.kind[i],
    h = L.hash[i],
    a = L.area[i];
  let c: RGB = L.palette[L.base[i]];

  // Global state: melting snow, rising seas, ocean health.
  if (k === KIND.snow && climate > meltThreshold(y, h))
    c = h & 1 ? C.rock : C.rockD;
  const rise = Math.floor(climate * 1.5);
  const tidehaven = a !== NONE && PROVINCES[a].civ === "tidehaven";
  if (
    rise > 0 &&
    L.distSea[i] <= rise &&
    (k === KIND.beach || (tidehaven && lowland(k)))
  )
    c = h < 40 ? C.flood : C.shallow;
  if (isSea(k) && ocean < 85)
    c = mix(c, C.murk, Math.min(0.6, (85 - ocean) / 100));

  // Ambient animation: water shimmer and drifting waves.
  if (k === KIND.water && (x + y * 3 - frame) % 11 === 0 && h < 110) c = C.foam;
  if (isSea(k) && h < 5 && ((frame + h) & 3) === 0) c = C.wave;

  // Hazards active in this area (sea tiles take the hazards of the nearest area).
  const owner = a !== NONE ? a : L.near[i];
  if (owner === NONE) return c;
  const fx = status[owner].effects;
  if (!fx.size) return c;
  const land = a !== NONE && !isSea(k);
  for (const e of fx) {
    if (
      (e === "flood" || e === "dam_failure") &&
      land &&
      lowland(k) &&
      L.distWater[i] <= 3
    ) {
      c =
        ((x + y + (frame >> 1)) & 3) === 0
          ? C.foam
          : h < 90
            ? C.shallow
            : C.flood;
    } else if (
      (e === "hurricane" || e === "tsunami" || e === "sea_rise") &&
      land &&
      lowland(k) &&
      L.distSea[i] <= 4
    ) {
      c = ((x - y + (frame >> 1)) & 3) === 0 ? C.foam : C.flood;
    } else if (
      (e === "wildfire" || e === "volcano") &&
      land &&
      (k === KIND.forest || k === KIND.grass || k === KIND.pasture)
    ) {
      if (k !== KIND.forest) c = h < 128 ? C.soil : C.dry;
      else if (h < 36 && (frame + h) % 3 === 0) c = h < 18 ? C.emberY : C.ember;
      else c = h < 128 ? C.ash : C.ashL;
    } else if (e === "spill" && (isSea(k) || k === KIND.water)) {
      const band = (x + 2 * y + (frame >> 1)) % 6;
      if (band === 0) c = C.sludge;
      else if (band === 1) c = C.sludgeD;
    } else if ((e === "smog" || e === "heatwave") && ((x + y) & 1) === 0) {
      c = mix(c, rgb(DISASTERS[e].color), 0.45);
    } else if (e === "drought" && land) {
      // Patchy, not total: keeps the area readable while showing it has dried out.
      if (
        (k === KIND.grass || k === KIND.pasture || k === KIND.field) &&
        h < 110
      )
        c = mix(c, h < 55 ? C.dry : C.soil, 0.7);
      else if (k === KIND.water && x & 1) c = C.flood;
    } else if ((e === "earthquake" || e === "landslide") && land) {
      if ((x + (y >> 1) * 3) % 23 === 0 && h < 150) c = C.ink;
      else if (e === "landslide" && L.distWater[i] <= 2 && h < 100) c = C.soil;
    } else if (e === "grid_failure" && land) {
      c = mix(c, C.ink, 0.35);
    }
  }
  return c;
}

// ---------- sprites ----------
interface Sprite {
  rows: string[];
  pal: Record<string, string>;
}
const BUILDING_SPRITES: Record<string, Sprite> = {
  farm: {
    rows: ["OOOOOOO", "OWWWWWO", "OwwwwwO", "OWWWWWO", "OOOOOOO"],
    pal: { O: "#6e4c2a", W: "#d9bb4a", w: "#b8982e" },
  },
  solar: {
    rows: ["NnNnNn", "nNnNnN", "NnNnNn", ".|..|."],
    pal: { N: "#2a3b6e", n: "#4a63a8", "|": "#6b6b72" },
  },
  wind: {
    rows: ["x.x", ".x.", "x|x", ".|.", ".|.", ".|."],
    pal: { x: "#f4f4ec", "|": "#f4f4ec" },
  },
  dam: {
    rows: ["OOOOOOO", "OLLLLLO", "OOOOOOO"],
    pal: { O: "#1a120a", L: "#cfc8b6" },
  },
  levee: { rows: ["GGGGGGG", "SSSSSSS"], pal: { G: "#4f8a32", S: "#8a6238" } },
  seawall: {
    rows: ["LMLMLML", "MLMLMLM", "OOOOOOO"],
    pal: { L: "#cfc8b6", M: "#9a9182", O: "#1a120a" },
  },
  vertical: {
    rows: [".OO.", "OGGO", "OgGO", "OGgO", "OgGO", "OGGO", "OOOO"],
    pal: { O: "#1a120a", G: "#7fd65a", g: "#cfc8b6" },
  },
  desal: {
    rows: [".WWW.", "WWbWW", "OOOOO", "bbbbb"],
    pal: { W: "#f4f4ec", b: "#3a9bd2", O: "#1a120a" },
  },
  geothermal: {
    rows: ["..s..", ".OrO.", "OrrrO"],
    pal: { O: "#3a3632", r: "#e8642c", s: "#c9c9c9" },
  },
  rig: {
    rows: ["..O..", ".O.O.", ".OOO.", "O.O.O", "OOOOO"],
    pal: { O: "#1a120a" },
  },
  reserve: {
    rows: [".SS.", "SssS", "SssS", "SssS", "OOOO"],
    pal: { S: "#d9bb4a", s: "#b8982e", O: "#1a120a" },
  },
  storage: {
    rows: [".OO.", "OyyO", "OYyO", "OyyO", "OOOO"],
    pal: { O: "#1a120a", y: "#f5c542", Y: "#f4f4ec" },
  },
  shelter: {
    rows: ["..R..", ".RRR.", "RRRRR", ".WdW.", ".WdW."],
    pal: { R: "#c8402c", W: "#efe2bc", d: "#3e2414" },
  },
  lab: {
    rows: [".BBBB.", "BBBBBB", "WbWWbW", "WWWWWW", "OOOOOO"],
    pal: { B: "#4a63a8", W: "#f4f4ec", b: "#3a9bd2", O: "#1a120a" },
  },
  port: { rows: ["P.P.P.P", "PPPPPPP"], pal: { P: "#8a5a32" } },
  restoration: {
    rows: [".g.", "gGg", ".t."],
    pal: { g: "#7fd65a", G: "#3d7a2e", t: "#5a3a1e" },
  },
};
const TURBINE_SPIN = [".x.", "xxx", ".|.", ".|.", ".|.", ".|."];

function blit(
  out: Uint8ClampedArray,
  rows: string[],
  pal: Record<string, string | RGB | undefined>,
  x0: number,
  y0: number,
  skip?: (ch: string, i: number, j: number) => boolean,
) {
  rows.forEach((row, j) => {
    for (let i = 0; i < row.length; i++) {
      const ch = row[i];
      const v = pal[ch];
      if (ch === "." || ch === " " || v === undefined || skip?.(ch, i, j))
        continue;
      const x = x0 + i,
        y = y0 + j;
      if (x < 0 || y < 0 || x >= MAP_W || y >= MAP_H) continue;
      const c = typeof v === "string" ? rgb(v) : v,
        o = (y * MAP_W + x) * 4;
      out[o] = c[0];
      out[o + 1] = c[1];
      out[o + 2] = c[2];
      out[o + 3] = 255;
    }
  });
}
function puff(
  out: Uint8ClampedArray,
  x: number,
  y: number,
  frame: number,
  dark = false,
) {
  for (let p = 0; p < 3; p++) {
    const py = y - ((frame + p * 2) % 6),
      px = x + (p % 2);
    blit(out, ["s"], { s: dark ? C.smokeD : C.smoke }, px, py);
  }
}
/** Free spots beside a castle (left/right, never under its nameplate). */
function buildingSpot(
  L: WorldLayers,
  cx: number,
  cy: number,
  w: number,
  h: number,
  sprite: Sprite,
  n: number,
) {
  const sw = sprite.rows[0].length,
    sh = sprite.rows.length;
  const anchors = [
    [-sw - 2, h - sh],
    [w + 1, h - sh],
    [-sw - 2, h - sh - 8],
    [w + 1, h - sh - 8],
    [-sw * 2 - 4, h - sh],
    [w + sw + 3, h - sh],
    [-sw * 2 - 4, h - sh - 8],
    [w + sw + 3, h - sh - 8],
  ];
  const ok = (x: number, y: number) => {
    for (let j = 0; j < sh; j++)
      for (let i = 0; i < sw; i++) {
        const xx = x + i,
          yy = y + j;
        if (xx < 0 || yy < 0 || xx >= MAP_W || yy >= MAP_H) return false;
        if (L.kind[yy * MAP_W + xx] <= KIND.water) return false;
      }
    return true;
  };
  let found = 0;
  for (const [dx, dy] of anchors) {
    const x = cx + dx,
      y = cy + dy;
    if (ok(x, y) && found++ === n) return [x, y];
  }
  return undefined;
}

/** Draw the whole world for `state` at animation `frame` into an RGBA buffer of MAP_W × MAP_H. */
export function renderWorld(
  state: GameState | undefined,
  frame: number,
  out: Uint8ClampedArray,
) {
  const L = worldLayers();
  const status = areaStatus(state);
  const climate = state?.climate ?? 0;
  const ocean = state?.ocean ?? 100;
  for (let i = 0; i < MAP_W * MAP_H; i++) {
    const c = terrainPixel(L, i, frame, status, climate, ocean);
    out[i * 4] = c[0];
    out[i * 4 + 1] = c[1];
    out[i * 4 + 2] = c[2];
    out[i * 4 + 3] = 255;
  }
  const areaAt = (x: number, y: number) =>
    L.area[Math.min(MAP_H - 1, Math.max(0, y)) * MAP_W + x];
  for (const s of world.sprites) {
    const fx =
      status[areaAt(s.x + 1, s.y + s.rows.length - 1)]?.effects ??
      new Set<string>();
    if (s.kind === "factory") {
      blit(out, s.rows, s.pal, s.x, s.y, (ch) => ch === "s");
      puff(out, s.x + 3, s.y + 1, frame, fx.has("smog"));
    } else if (s.kind === "turbine") {
      blit(out, frame & 1 ? TURBINE_SPIN : s.rows, s.pal, s.x, s.y);
    } else if (s.kind === "boat") {
      blit(out, s.rows, s.pal, s.x, s.y + ((frame >> 1) & 1));
    } else if (s.kind === "lighthouse") {
      const on = frame % 4 < 2;
      blit(out, s.rows, { ...s.pal, y: on ? "#fff1b0" : "#3e2414" }, s.x, s.y);
      if (on) blit(out, ["y...y"], { y: "#f5c542" }, s.x - 1, s.y);
    } else if (s.kind === "dam") {
      const broken = fx.has("dam_failure");
      blit(
        out,
        s.rows,
        s.pal,
        s.x,
        s.y,
        (_, i, j) => broken && j < 3 && i >= 4 && i <= 6,
      );
    } else {
      blit(out, s.rows, s.pal, s.x, s.y);
    }
  }
  world.castles.forEach((k, a) => {
    const p = PROVINCES[a],
      w = k.rows[0].length,
      h = k.rows.length,
      st = status[a];
    st.buildings.forEach((id, n) => {
      const sprite = BUILDING_SPRITES[id] ?? BUILDING_SPRITES.shelter;
      const spot = buildingSpot(L, k.x, k.y, w, h, sprite, n);
      if (!spot) return;
      const rows = id === "wind" && frame & 1 ? TURBINE_SPIN : sprite.rows;
      blit(out, rows, sprite.pal, spot[0], spot[1]);
      if (id === "geothermal") puff(out, spot[0] + 2, spot[1] - 1, frame);
    });
    blit(out, k.rows, { ...k.pal, F: FLAG[p.civ] }, k.x, k.y);
    if (st.damaged > 0) {
      puff(out, k.x + 2, k.y + 2, frame, true);
      puff(out, k.x + w - 3, k.y + 3, frame + 3, true);
    }
  });
}
