/**
 * Live pixel renderer for the world map.
 *
 * The terrain comes from src/data/worldmap.json (generated by tools/worldmap.py): a base colour layer,
 * a terrain-kind layer and an area layer (one area per civilization). Every frame we recolour tiles
 * from game state — this cycle's events, melting snow and rising seas as the climate warms — then
 * draw the animated scenery (boats, lighthouse, dam) and each town: its keep plus every building the
 * player has built, filling the town's plots nearest-first so the town visibly grows.
 * Pure function over a pixel buffer: no DOM, so it is testable in Node.
 */
import world from "../../../../src/data/worldmap.json";
import oceanData from "../../../../src/data/ocean.json";
import fireData from "../../../../src/data/wildfire.json";
import { EVENTS } from "./content";
import { spillTarget } from "./engine";
import { OWNERS, TOWNS } from "./towns";
import { CIV_IDS, type CivId, type GameState } from "./types";

export const MAP_W = world.w;
export const MAP_H = world.h;
export const OCEAN = oceanData;
type RGB = [number, number, number];
const rgb = (hex: string): RGB => [
  parseInt(hex.slice(1, 3), 16),
  parseInt(hex.slice(3, 5), 16),
  parseInt(hex.slice(5, 7), 16),
];
const KIND = Object.fromEntries(world.kinds.map((k, i) => [k, i])) as Record<
  string,
  number
>;
const NONE = 255;

const C = {
  deep: rgb(OCEAN.deep),
  sea: rgb("#21497a"),
  crest: rgb(OCEAN.crest),
  ink: rgb("#1a120a"),
  rock: rgb("#776e60"),
  rockD: rgb("#5c554a"),
  shallow: rgb("#2b6fa0"),
  flood: rgb("#6ab8cc"),
  foam: rgb("#9fd6e4"),
  wave: rgb("#3b6ea8"),
  murk: rgb("#3c5446"),
  ash: rgb("#3a3632"),
  ashL: rgb("#4e4842"),
  ember: rgb("#e8642c"),
  emberY: rgb("#f5c542"),
  soil: rgb("#8a6238"),
  dry: rgb("#b8982e"),
  sludge: rgb("#6e6230"),
  sludgeD: rgb("#4e4520"),
  smoke: rgb("#c9c9c9"),
  smokeD: rgb("#6b6b72"),
};
const FLAG: Record<string, RGB> = {
  highland: rgb("#a07ad6"),
  verdant: rgb("#7fd65a"),
  forge: rgb("#f08a3c"),
  tidehaven: rgb("#46d6d0"),
};

export interface WorldLayers {
  base: Uint8Array;
  palette: RGB[];
  kind: Uint8Array;
  area: Uint8Array;
  near: Uint8Array;
  distWater: Uint8Array;
  distSea: Uint8Array;
  hash: Uint8Array;
}

function unrle(runs: number[]): Uint8Array {
  const out = new Uint8Array(MAP_W * MAP_H);
  let o = 0;
  for (let i = 0; i < runs.length; i += 2) {
    out.fill(runs[i], o, o + runs[i + 1]);
    o += runs[i + 1];
  }
  return out;
}
function fromBase64(s: string): Uint8Array {
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
/** 4-neighbour distance (capped at 255) from every tile matching `source`. */
function distance(kind: Uint8Array, source: (k: number) => boolean) {
  const dist = new Uint8Array(kind.length).fill(255);
  let frontier: number[] = [];
  kind.forEach((k, i) => {
    if (source(k)) {
      dist[i] = 0;
      frontier.push(i);
    }
  });
  for (let d = 1; d < 255 && frontier.length; d++) {
    const next: number[] = [];
    for (const i of frontier) {
      const x = i % MAP_W;
      for (const j of [
        i - MAP_W,
        i + MAP_W,
        x > 0 ? i - 1 : -1,
        x < MAP_W - 1 ? i + 1 : -1,
      ])
        if (j >= 0 && j < kind.length && dist[j] === 255) {
          dist[j] = d;
          next.push(j);
        }
    }
    frontier = next;
  }
  return dist;
}

let cached: WorldLayers | undefined;
export function worldLayers(): WorldLayers {
  if (cached) return cached;
  const kind = unrle(world.kind);
  const hash = new Uint8Array(MAP_W * MAP_H);
  for (let i = 0; i < hash.length; i++) {
    let h = Math.imul(i ^ 0x9e3779b9, 0x85ebca6b);
    h = Math.imul(h ^ (h >>> 13), 0xc2b2ae35);
    hash[i] = (h ^ (h >>> 16)) & 255;
  }
  cached = {
    base: fromBase64(world.base),
    palette: world.palette.map(rgb),
    kind,
    area: unrle(world.area),
    near: unrle(world.near),
    distWater: distance(kind, (k) => k <= KIND.water),
    distSea: distance(kind, (k) => k <= KIND.shallow),
    hash,
  };
  return cached;
}

const isSea = (k: number) => k <= KIND.shallow;
const lowland = (k: number) =>
  k === KIND.grass ||
  k === KIND.pasture ||
  k === KIND.field ||
  k === KIND.marsh ||
  k === KIND.beach ||
  k === KIND.forest;
const mix = (a: RGB, b: RGB, t: number): RGB => [
  a[0] + (b[0] - a[0]) * t,
  a[1] + (b[1] - a[1]) * t,
  a[2] + (b[2] - a[2]) * t,
];

/** One world-coordinate texture for the entire sea, including beyond the map bounds. */
export function seaPixel(
  x: number,
  y: number,
  frame: number,
  climate = 0,
  shallow = false,
): RGB {
  const drift = Math.floor(frame / OCEAN.shimmer.framesPerDrift);
  const step = Math.floor(frame / OCEAN.shimmer.framesPerStep);
  const anchor = Math.floor((x - drift) / 2) * 2 + y * MAP_W;
  let h = Math.imul(anchor ^ 0x9e3779b9, 0x85ebca6b);
  h = Math.imul(h ^ (h >>> 13), 0xc2b2ae35);
  const noise = (h ^ (h >>> 16)) & 255;
  let c = shallow ? C.sea : C.deep;
  if (noise < OCEAN.shimmer.density && ((step + noise) & 3) < 3) c = C.wave;
  const health = 100 - climate * 12;
  if (health < 85) c = mix(c, C.murk, Math.min(0.6, (85 - health) / 100));
  return c;
}

export interface PortTraffic {
  civ: CivId;
  frame: number;
}
/** Trade notices are synchronized through the pure reducer and SpacetimeDB state. */
export function tradeTraffic(
  state: GameState | undefined,
  frame: number,
): PortTraffic[] {
  return (state?.news ?? [])
    .filter((n) => n.kind === "trade" && n.round === state?.round && n.civ)
    .slice(-OCEAN.trade.maxBoats)
    .map((n, i) => ({
      civ: n.civ!,
      frame: (frame + i * 7) % OCEAN.trade.frames,
    }));
}

const routes = new Map<CivId, [number, number][]>();
/** Find a berth and a connected sailing route. Ships never cross land tiles. */
export function portRoute(civ: CivId): [number, number][] {
  const cachedRoute = routes.get(civ);
  if (cachedRoute) return cachedRoute;
  const L = worldLayers();
  const anchor = OCEAN.ports[civ];
  let start = -1,
    closest = Infinity;
  for (let i = 0; i < L.kind.length; i++) {
    if (L.kind[i] > KIND.water) continue;
    const d =
      Math.abs((i % MAP_W) - anchor[0]) +
      Math.abs(Math.floor(i / MAP_W) - anchor[1]);
    if (d < closest) {
      start = i;
      closest = d;
    }
  }
  const parents = new Map<number, number>([[start, -1]]);
  let frontier = [start],
    end = start;
  for (
    let step = 0;
    step < OCEAN.trade.routeLength && frontier.length;
    step++
  ) {
    const next: number[] = [];
    for (const i of frontier) {
      const x = i % MAP_W;
      for (const j of [
        x > 0 ? i - 1 : -1,
        x < MAP_W - 1 ? i + 1 : -1,
        i - MAP_W,
        i + MAP_W,
      ]) {
        if (
          j < 0 ||
          j >= L.kind.length ||
          L.kind[j] > KIND.water ||
          parents.has(j)
        )
          continue;
        parents.set(j, i);
        next.push(j);
        end = j;
      }
    }
    frontier = next;
  }
  const path: [number, number][] = [];
  for (let i = end; i >= 0; i = parents.get(i) ?? -1)
    path.push([i % MAP_W, Math.floor(i / MAP_W)]);
  path.reverse();
  routes.set(civ, path);
  return path;
}

export function tsunamiDirection(state: GameState): string {
  return OCEAN.tsunami.sides[
    ((state.seed >>> 0) + state.round) % OCEAN.tsunami.sides.length
  ];
}

export interface WorldView {
  width: number;
  height: number;
  originX: number;
  originY: number;
  /** The map's safe area; waves and sea continue behind the surrounding UI. */
  clip: { left: number; top: number; right: number; bottom: number };
}

/** Composite the island and extended sea on one pixel grid and one animation clock. */
export function renderWorldView(
  state: GameState | undefined,
  frame: number,
  out: Uint8ClampedArray,
  view: WorldView,
  traffic = tradeTraffic(state, frame),
) {
  const { width, height, originX, originY, clip } = view;
  for (let y = 0; y < height; y++)
    for (let x = 0; x < width; x++) {
      const c = seaPixel(x - originX, y - originY, frame, state?.climate);
      const o = (y * width + x) * 4;
      out[o] = c[0];
      out[o + 1] = c[1];
      out[o + 2] = c[2];
      out[o + 3] = 255;
    }
  const island = new Uint8ClampedArray(MAP_W * MAP_H * 4);
  renderWorld(state, frame, island, traffic);
  for (let y = 0; y < MAP_H; y++)
    for (let x = 0; x < MAP_W; x++) {
      const tx = x + originX,
        ty = y + originY;
      if (
        tx < 0 ||
        ty < 0 ||
        tx >= width ||
        ty >= height ||
        tx < clip.left ||
        ty < clip.top ||
        tx >= clip.right ||
        ty >= clip.bottom
      )
        continue;
      const o = (ty * width + tx) * 4,
        i = (y * MAP_W + x) * 4;
      out.set(island.subarray(i, i + 4), o);
    }
  const active =
    state &&
    state.phase !== "ended" &&
    areaStatus(state).some((a) => a.effects.has("tsunami"));
  if (!active) return;
  const side = tsunamiDirection(state);
  const alongX = side !== "south",
    extent = alongX ? width : height;
  const progress = (frame % OCEAN.tsunami.frames) / (OCEAN.tsunami.frames - 1);
  const front = Math.floor(-12 + progress * (extent + 24));
  const L = worldLayers();
  for (let y = 0; y < height; y++)
    for (let x = 0; x < width; x++) {
      const wx = x - originX,
        wy = y - originY;
      const inMap = wx >= 0 && wy >= 0 && wx < MAP_W && wy < MAP_H;
      const i = wy * MAP_W + wx;
      // Only the sea and low coastal ground are swept. Inland hills remain readable.
      if (
        inMap &&
        L.kind[i] > KIND.water &&
        (L.distSea[i] > OCEAN.tsunami.coastalReach || !lowland(L.kind[i]))
      )
        continue;
      const axis =
        side === "east" ? width - 1 - x : side === "south" ? height - 1 - y : x;
      const bend = Math.floor((alongX ? y : x) / 9) % 3;
      const d = front + bend - axis;
      if (d < 0 || d >= OCEAN.tsunami.width) continue;
      const c = d < 2 ? C.crest : d < 4 ? C.foam : d < 6 ? C.flood : C.shallow;
      const o = (y * width + x) * 4;
      out[o] = c[0];
      out[o + 1] = c[1];
      out[o + 2] = c[2];
    }
}

export interface AreaStatus {
  effects: Set<string>;
  buildings: string[];
  damaged: number;
}
/** What is happening in each town's region right now. */
export function areaStatus(state?: GameState): AreaStatus[] {
  return TOWNS.map((t) => {
    const civ = OWNERS[t.civ];
    const effects = new Set<string>();
    let damaged = 0;
    if (state && state.phase !== "ended") {
      const own = state.events[civ];
      const avoided = state.phase === "build" && state.civs[civ].choice === 0;
      if (own && !avoided) {
        effects.add(own.type);
        damaged = 1;
      }
      // Hazards a neighbor's cheap choice pushed onto this region.
      if (state.phase === "build")
        for (const other of CIV_IDS) {
          const e = EVENTS[state.events[other]?.type];
          if (
            other === civ ||
            state.civs[other].choice !== 0 ||
            !e?.cheap.spillTo
          )
            continue;
          if (spillTarget(other, e.cheap.spillTo) === civ) {
            effects.add(state.events[other].type);
            damaged = 1;
          }
        }
    }
    return {
      effects,
      buildings: state
        ? ["house", "house", ...state.civs[civ].buildings]
        : ["house", "house"],
      damaged,
    };
  });
}
/** Snow at lower altitude melts first as the planet warms (climate is °C above baseline). */
const meltThreshold = (y: number, h: number) =>
  3 - (Math.min(y, 50) / 50) * 2.6 + (h / 255 - 0.5) * 0.4;

const fuel = (kind: number) =>
  kind === KIND.forest || kind === KIND.grass || kind === KIND.pasture;
let lastFireKey = "";
let lastFireMask = new Float32Array(MAP_W * MAP_H);

/** Small, connected burn patches taper through pixel dither. Borders never constrain spread. */
export function wildfireMask(
  state?: GameState,
  status = areaStatus(state),
): Float32Array {
  const active = TOWNS.flatMap((t, i) =>
    status[i].effects.has("wildfire") ? [OWNERS[t.civ]] : [],
  );
  const key = `${state?.seed}:${state?.round}:${active.map((c) => `${c}:${state?.civs[c].buildings.includes("firewatch")}`).join("|")}`;
  if (key === lastFireKey) return lastFireMask;
  const mask = new Float32Array(MAP_W * MAP_H);
  const L = worldLayers();
  for (const civ of active) {
    const owner = TOWNS.findIndex((t) => OWNERS[t.civ] === civ);
    const protectedTown = state?.civs[civ].buildings.includes("firewatch");
    const seed =
      ((state?.seed ?? 0) ^
        Math.imul(state?.round ?? 1, 31) ^
        (owner * 997)) >>>
      0;
    for (const [n, zone] of fireData.zones[civ].entries()) {
      const [ax, ay, size] = zone;
      const cx = ax + ((seed + n * 13) % 9) - 4;
      const cy = ay + ((seed + n * 7) % 7) - 3;
      let start = -1,
        best = Infinity;
      for (let i = 0; i < L.kind.length; i++) {
        if (L.area[i] !== owner || !fuel(L.kind[i])) continue;
        const d =
          Math.abs((i % MAP_W) - cx) +
          Math.abs(Math.floor(i / MAP_W) - cy) +
          (L.kind[i] === KIND.forest ? 0 : 5);
        if (d < best) {
          best = d;
          start = i;
        }
      }
      if (start < 0) continue;
      const radius = Math.round(size * (protectedTown ? 0.75 : 1));
      const seen = new Uint8Array(MAP_W * MAP_H);
      let frontier = [start];
      seen[start] = 1;
      for (let d = 0; d < radius && frontier.length; d++) {
        const next: number[] = [];
        for (const i of frontier) {
          const x = i % MAP_W,
            y = Math.floor(i / MAP_W);
          // Coarse noise makes lobes and unburnt islands; fine dither feathers their edges.
          const block =
            L.hash[Math.floor(y / 5) * 5 * MAP_W + Math.floor(x / 5) * 5] / 255;
          const strength = Math.max(
            0,
            (1 - d / radius) * (0.55 + block * 0.45),
          );
          mask[i] = Math.max(mask[i], strength);
          for (const j of [
            x > 0 ? i - 1 : -1,
            x < MAP_W - 1 ? i + 1 : -1,
            i - MAP_W,
            i + MAP_W,
          ]) {
            if (j < 0 || j >= L.kind.length || seen[j] || !fuel(L.kind[j]))
              continue;
            seen[j] = 1;
            next.push(j);
          }
        }
        frontier = next;
      }
    }
  }
  lastFireKey = key;
  lastFireMask = mask;
  return mask;
}

function terrainPixel(
  L: WorldLayers,
  i: number,
  frame: number,
  status: AreaStatus[],
  climate: number,
  ocean: number,
  fire: Float32Array,
): RGB {
  const x = i % MAP_W,
    y = (i / MAP_W) | 0,
    k = L.kind[i],
    h = L.hash[i],
    a = L.area[i];
  let c: RGB = L.palette[L.base[i]];
  if (k === KIND.deep || k === KIND.sea)
    c = seaPixel(x, y, frame, climate, k === KIND.sea);

  // Global state: melting snow, rising seas, ocean health.
  if (k === KIND.snow && climate > meltThreshold(y, h))
    c = h & 1 ? C.rock : C.rockD;
  const rise = Math.floor(climate * 1.5);
  const tidehaven = a !== NONE && TOWNS[a].civ === "tidehaven";
  if (
    rise > 0 &&
    L.distSea[i] <= rise &&
    (k === KIND.beach || (tidehaven && lowland(k)))
  )
    c = h < 40 ? C.flood : C.shallow;
  if (k === KIND.shallow && ocean < 85)
    c = mix(c, C.murk, Math.min(0.6, (85 - ocean) / 100));

  // Ambient animation: water shimmer and drifting waves.
  const riverStep = Math.floor(frame / OCEAN.shimmer.riverFramesPerStep);
  const seaStep = Math.floor(frame / OCEAN.shimmer.framesPerStep);
  if (k === KIND.water && (x + y * 3 - riverStep) % 11 === 0 && h < 70)
    c = C.foam;
  if (
    k === KIND.shallow &&
    h < OCEAN.shimmer.density &&
    ((seaStep + h) & 3) === 0
  )
    c = C.wave;

  // Apply the terrain-connected mask independently of ownership, including over a border.
  const strength = fire[i];
  if (strength > 0 && h / 255 < strength) {
    c = mix(c, h & 1 ? C.ash : C.ashL, strength * fireData.sootStrength);
    const flicker = Math.floor(frame / fireData.framesPerFlicker);
    if (
      strength > 0.35 &&
      h < fireData.emberThreshold &&
      ((flicker + h) & 3) < 3
    )
      c = (flicker + h) & 1 ? C.ember : C.emberY;
  }

  // Hazards active in this area (sea tiles take the hazards of the nearest area).
  const owner = a !== NONE ? a : L.near[i];
  if (owner === NONE) return c;
  const fx = status[owner].effects;
  if (!fx.size) return c;
  const land = a !== NONE && !isSea(k);
  for (const e of fx) {
    if (
      (e === "flood" || e === "dam_failure") &&
      land &&
      lowland(k) &&
      L.distWater[i] <= 3
    ) {
      c =
        ((x + y + (frame >> 1)) & 3) === 0
          ? C.foam
          : h < 90
            ? C.shallow
            : C.flood;
    } else if (
      (e === "hurricane" || e === "tsunami" || e === "sea_rise") &&
      land &&
      lowland(k) &&
      L.distSea[i] <= 4
    ) {
      c = ((x - y + (frame >> 1)) & 3) === 0 ? C.foam : C.flood;
    } else if (
      e === "volcano" &&
      land &&
      (k === KIND.forest || k === KIND.grass || k === KIND.pasture)
    ) {
      if (k !== KIND.forest) c = h < 128 ? C.soil : C.dry;
      else if (h < 36 && (frame + h) % 3 === 0) c = h < 18 ? C.emberY : C.ember;
      else c = h < 128 ? C.ash : C.ashL;
    } else if (e === "spill" && (isSea(k) || k === KIND.water)) {
      const band = (x + 2 * y + (frame >> 1)) % 6;
      if (band === 0) c = C.sludge;
      else if (band === 1) c = C.sludgeD;
    } else if ((e === "smog" || e === "heatwave") && (x + 2 * y) % 5 === 0) {
      c = mix(c, rgb(EVENTS[e as keyof typeof EVENTS].color), 0.5);
    } else if (e === "drought" && land) {
      // Patchy, not total: keeps the area readable while showing it has dried out.
      if (
        (k === KIND.grass || k === KIND.pasture || k === KIND.field) &&
        h < 110
      )
        c = mix(c, h < 55 ? C.dry : C.soil, 0.7);
      else if (k === KIND.water && x & 1) c = C.flood;
    } else if ((e === "earthquake" || e === "landslide") && land) {
      if ((x + (y >> 1) * 3) % 23 === 0 && h < 150) c = C.ink;
      else if (e === "landslide" && L.distWater[i] <= 2 && h < 100) c = C.soil;
    } else if (e === "grid_failure" && land) {
      c = mix(c, C.ink, 0.35);
    }
  }
  return c;
}

// ---------- sprites ----------
interface Sprite {
  rows: string[];
  pal: Record<string, string>;
}
const BUILDING_SPRITES: Record<string, Sprite> = {
  house: {
    rows: ["..R..", ".RRR.", "RRRRR", ".WWW.", ".WdW."],
    pal: { R: "#c8402c", W: "#efe2bc", d: "#3e2414" },
  },
  farm: {
    rows: ["OOOOOOO", "OWWWWWO", "OwwwwwO", "OWWWWWO", "OOOOOOO"],
    pal: { O: "#6e4c2a", W: "#d9bb4a", w: "#b8982e" },
  },
  pasture: {
    rows: ["F.F.F.F", "FFFFFFF", ".w..w..", ".wO.wO.", "FFFFFFF"],
    pal: { F: "#8a5a32", w: "#f4f4ec", O: "#1a120a" },
  },
  lumber: {
    rows: ["t..t.t.", "LLLLLL.", ".LLLLLL", "t.t..t."],
    pal: { t: "#5a3a1e", L: "#b07a45" },
  },
  grove: {
    rows: [".g...g.", "ggg.ggg", "gGg.gGg", ".t...t."],
    pal: { g: "#4f8f36", G: "#2d5e22", t: "#5a3a1e" },
  },
  kiln: {
    rows: ["..OOO..", ".ORRRO.", ".ORfRO.", ".OOOOO."],
    pal: { O: "#1a120a", R: "#d0613f", f: "#f5c542" },
  },
  mine: {
    rows: ["..KKK..", ".KdddK.", "KdddddK", "PPPPPPP"],
    pal: { K: "#776e60", d: "#1a120a", P: "#8a5a32" },
  },
  windmill: {
    rows: ["x.x", ".x.", "x.x", ".B.", ".B.", "BBB"],
    pal: { x: "#f4f4ec", B: "#8a5a32" },
  },
  wetland: {
    rows: ["b.g.b.g", "bbgbbbg", "gbbbgbb"],
    pal: { b: "#3a9bd2", g: "#4f8a32" },
  },
  cistern: {
    rows: [".OOO.", "ObbbO", "ObbbO", ".OOO."],
    pal: { O: "#9a9182", b: "#3a9bd2" },
  },
  firewatch: {
    rows: [".R.", "OOO", ".O.", ".O.", "O.O"],
    pal: { R: "#c8402c", O: "#8a5a32" },
  },
  terraces: {
    rows: ["GGGGG..", "SSSSS..", ".GGGGGG", ".SSSSSS"],
    pal: { G: "#5e9c3c", S: "#8a6238" },
  },
  filters: {
    rows: [".g.", "OOO", "OMO", "OMO", "OOO"],
    pal: { g: "#7fd65a", O: "#1a120a", M: "#9a9182" },
  },
  settling: {
    rows: ["OOOOOOO", "OsbsbsO", "OOOOOOO"],
    pal: { O: "#9a9182", s: "#6e6230", b: "#3a9bd2" },
  },
  mangroves: {
    rows: [".g.g.g.", "ggggggg", "t.t.t.t", "bbbbbbb"],
    pal: { g: "#2d5e22", t: "#5a3a1e", b: "#3a9bd2" },
  },
  shade: {
    rows: [".g..g.", "gggggg", "gGggGg", ".t..t."],
    pal: { g: "#6fae48", G: "#3d7a2e", t: "#5a3a1e" },
  },
  refuge: {
    rows: ["..RRR..", ".RRRRR.", "RRRRRRR", ".WWWWW.", ".WWdWW."],
    pal: { R: "#f5c542", W: "#efe2bc", d: "#3e2414" },
  },
};
const WINDMILL_SPIN = [".x.", "xxx", ".x.", ".B.", ".B.", "BBB"];

function blit(
  out: Uint8ClampedArray,
  rows: string[],
  pal: Record<string, string | RGB | undefined>,
  x0: number,
  y0: number,
  skip?: (ch: string, i: number, j: number) => boolean,
) {
  rows.forEach((row, j) => {
    for (let i = 0; i < row.length; i++) {
      const ch = row[i];
      const v = pal[ch];
      if (ch === "." || ch === " " || v === undefined || skip?.(ch, i, j))
        continue;
      const x = x0 + i,
        y = y0 + j;
      if (x < 0 || y < 0 || x >= MAP_W || y >= MAP_H) continue;
      const c = typeof v === "string" ? rgb(v) : v,
        o = (y * MAP_W + x) * 4;
      out[o] = c[0];
      out[o + 1] = c[1];
      out[o + 2] = c[2];
      out[o + 3] = 255;
    }
  });
}
function puff(
  out: Uint8ClampedArray,
  x: number,
  y: number,
  frame: number,
  dark = false,
) {
  for (let p = 0; p < 3; p++) {
    const py = y - ((frame + p * 2) % 6),
      px = x + (p % 2);
    blit(out, ["s"], { s: dark ? C.smokeD : C.smoke }, px, py);
  }
}
/** Draw the whole world for `state` at animation `frame` into an RGBA buffer of MAP_W × MAP_H. */
export function renderWorld(
  state: GameState | undefined,
  frame: number,
  out: Uint8ClampedArray,
  traffic: PortTraffic[] = tradeTraffic(state, frame),
) {
  const L = worldLayers();
  const status = areaStatus(state);
  const fire = wildfireMask(state, status);
  const climate = state?.climate ?? 0;
  // Warmer seas are murkier seas.
  const ocean = 100 - climate * 12;
  for (let i = 0; i < MAP_W * MAP_H; i++) {
    const c = terrainPixel(L, i, frame, status, climate, ocean, fire);
    out[i * 4] = c[0];
    out[i * 4 + 1] = c[1];
    out[i * 4 + 2] = c[2];
    out[i * 4 + 3] = 255;
  }
  const areaAt = (x: number, y: number) =>
    L.area[Math.min(MAP_H - 1, Math.max(0, y)) * MAP_W + x];
  for (const sp of world.sprites) {
    const fx =
      status[areaAt(sp.x + 1, sp.y + sp.rows.length - 1)]?.effects ??
      new Set<string>();
    if (sp.kind === "boat") {
      blit(out, sp.rows, sp.pal, sp.x, sp.y + ((frame >> 1) & 1));
    } else if (sp.kind === "lighthouse") {
      const on = frame % 4 < 2;
      blit(
        out,
        sp.rows,
        { ...sp.pal, y: on ? "#fff1b0" : "#3e2414" },
        sp.x,
        sp.y,
      );
      if (on) blit(out, ["y...y"], { y: "#f5c542" }, sp.x - 1, sp.y);
    } else if (sp.kind === "dam") {
      const broken = fx.has("flood");
      blit(
        out,
        sp.rows,
        sp.pal,
        sp.x,
        sp.y,
        (_, i, j) => broken && j < 3 && i >= 4 && i <= 6,
      );
    } else {
      blit(out, sp.rows, sp.pal, sp.x, sp.y);
    }
  }
  world.castles.forEach((k, a) => {
    const town = TOWNS[a],
      w = k.rows[0].length,
      st = status[a];
    // The town grows into its plots, nearest the keep first, in the order things were built.
    st.buildings.forEach((id, n) => {
      const slot = k.slots[n];
      if (!slot) return;
      const sprite = BUILDING_SPRITES[id] ?? BUILDING_SPRITES.house;
      const sw = sprite.rows[0].length,
        sh = sprite.rows.length;
      const x = slot[0] + Math.floor((7 - sw) / 2),
        y = slot[1] + 7 - sh;
      const rows = id === "windmill" && frame & 1 ? WINDMILL_SPIN : sprite.rows;
      blit(out, rows, sprite.pal, x, y);
      if (id === "kiln") puff(out, x + 3, y - 1, frame + n);
    });
    blit(out, k.rows, { ...k.pal, F: FLAG[town.civ] }, k.x, k.y);
    if (st.damaged > 0) {
      const fireOnly = st.effects.size === 1 && st.effects.has("wildfire");
      const smokeFrame = fireOnly
        ? Math.floor(frame / fireData.framesPerSmokeStep)
        : frame;
      // A distant woodland fire does not automatically set every castle smoking.
      if (!fireOnly || fire[(k.y + 3) * MAP_W + k.x + 2] > 0.3) {
        puff(out, k.x + 2, k.y + 2, smokeFrame, true);
        puff(out, k.x + w - 3, k.y + 3, smokeFrame + 3, true);
      }
    }
  });
  // Each town has a berth; cargo sails out and returns after an actual bank exchange.
  for (const civ of CIV_IDS) {
    const [x, y] = portRoute(civ)[0];
    blit(out, ["PPPP", ".P.P"], { P: "#b07a45" }, x - 1, y);
  }
  for (const trip of traffic) {
    const route = portRoute(trip.civ);
    const t = trip.frame / OCEAN.trade.frames;
    const index = Math.min(
      route.length - 1,
      Math.floor((1 - Math.abs(t * 2 - 1)) * route.length),
    );
    const [x, y] = route[index];
    blit(
      out,
      ["..F..", "..FF.", "..F..", "BBBBB", ".BBB."],
      { F: FLAG[townOfVisual(trip.civ)], B: "#b07a45" },
      x - 2,
      y - 4 + ((frame >> 1) & 1),
    );
  }
}

const townOfVisual = (civ: CivId) =>
  TOWNS.find((t) => OWNERS[t.civ] === civ)!.civ;
